import { Collection, FamilyMember, Place, VoteRecord } from "@/lib/types";

export const familyMembers: FamilyMember[] = [
  { id: "fred", name: "Fred", role: "admin", emoji: "🏖️" },
  { id: "simona", name: "Simona", role: "member", emoji: "🍝" },
  { id: "david", name: "David", role: "member", emoji: "🌊" },
  { id: "philippe", name: "Philippe", role: "member", emoji: "☀️" },
];

export const places: Place[] = [
  {
    id: "lido-alghero",
    slug: "lido-di-alghero",
    title: "Lido di Alghero / San Giovanni",
    category: "beach",
    shortDescription: "The easiest no-car beach day from base.",
    longDescription:
      "A practical city-beach option for quick swims, evening walks, and low-effort family resets when nobody wants a drive.",
    area: "Alghero city beach",
    latitude: 40.5574,
    longitude: 8.3282,
    walkTimeMinutes: 18,
    priceLevel: "free",
    estimatedCostText: "Free beach with optional lidos",
    imageUrl:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["no car needed", "easy swim", "evening walk"],
    avoidIf: ["looking for wild scenery", "peak mid-morning crowds"],
    tags: ["Beach", "No car needed", "Easy", "Quick option"],
    localTip: "Best used for a first-day reset or a low-energy beach morning.",
    weatherNotes: "Works best on calm, hot days.",
    foodNotes: "Easy to pair with city lunch or gelato.",
    sourceLabel: "User planning document",
    badgeTone: "sand",
  },
  {
    id: "maria-pia",
    slug: "spiaggia-di-maria-pia",
    title: "Spiaggia di Maria Pia",
    category: "beach",
    shortDescription: "Family-friendly sand with calm clear water.",
    longDescription:
      "A classic Alghero beach choice with gentler conditions, easy logistics, and comfort when the family wants a relaxed all-rounder.",
    area: "North Alghero",
    latitude: 40.5817,
    longitude: 8.3093,
    driveTimeMinutes: 9,
    priceLevel: "budget",
    estimatedCostText: "Free public beach or paid umbrellas",
    imageUrl:
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["teen-friendly", "calm water", "easy beach day", "SUP nearby"],
    avoidIf: ["late arrival", "crowd-sensitive mornings"],
    tags: ["Beach", "Teen-friendly", "Calm water", "Beach club", "Good lunch"],
    localTip: "Aim for the farther Maria Pia sections and arrive around 09:00 to 09:30.",
    parkingNotes: "Easier than Le Bombarde but still busy in July and August.",
    foodNotes: "Lido Hermeu kiosk is handy for panini and cold dishes.",
    sourceLabel: "User document plus travel guides",
    badgeTone: "sea",
  },
  {
    id: "bombarde",
    slug: "le-bombarde",
    title: "Le Bombarde",
    category: "beach",
    shortDescription: "The energetic beach-day pick for teenagers and water toys.",
    longDescription:
      "Lively white sand, clear water, rental options, and a buzzier atmosphere make this one of the strongest family debate starters.",
    area: "North of Alghero",
    latitude: 40.6012,
    longitude: 8.2888,
    driveTimeMinutes: 15,
    priceLevel: "budget",
    bookingRequired: false,
    imageUrl:
      "https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["teenagers", "SUP", "kayak", "snorkelling", "lively beach day"],
    avoidIf: ["late arrival", "dislike of crowds"],
    tags: ["Beach", "Teen-friendly", "Snorkelling", "SUP", "Kayak", "Good lunch"],
    localTip: "Try the left side near the red rocks for better scenery and slightly less crowding.",
    weatherNotes: "Best on calm hot days. Show up by 08:30 to 09:00.",
    parkingNotes: "Parking fills early in high season.",
    foodNotes: "Il Chiosco and Da Bruno make it easy to stay all day.",
    sourceLabel: "User document plus Alghero Life",
    badgeTone: "coral",
  },
  {
    id: "lazzaretto",
    slug: "lazzaretto",
    title: "Lazzaretto",
    category: "beach",
    shortDescription: "Coves and snorkelling when Le Bombarde feels too full.",
    longDescription:
      "A useful nearby swap that still gives you that pretty north-coast water without the exact same crowd profile.",
    area: "Near Le Bombarde",
    latitude: 40.6036,
    longitude: 8.2864,
    driveTimeMinutes: 16,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["snorkelling", "coves", "backup plan"],
    avoidIf: ["wanting easiest setup"],
    tags: ["Beach", "Snorkelling", "Avoid crowds", "Adventure"],
    localTip: "Best kept ready as Plan B for crowded north-coast mornings.",
    sourceLabel: "User planning document",
    badgeTone: "leaf",
  },
  {
    id: "mugoni",
    slug: "mugoni-beach",
    title: "Mugoni Beach",
    category: "beach",
    shortDescription: "The calm-water comfort choice for a full day.",
    longDescription:
      "Porto Conte bay gives this beach a more sheltered feel, making it one of the smartest picks on windy or stress-free family days.",
    area: "Porto Conte",
    latitude: 40.5872,
    longitude: 8.2115,
    driveTimeMinutes: 20,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1468413253725-0d5181091126?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["calm water", "comfort", "SUP", "canoe", "full-day beach"],
    avoidIf: ["seeking dramatic wild scenery"],
    tags: ["Beach", "Calm water", "Beach club", "Good lunch", "SUP"],
    localTip: "A smart fallback when west-facing beaches feel too exposed.",
    weatherNotes: "Preferred during stronger Maestrale days.",
    foodNotes: "Le Ninfe makes lunch logistics easy.",
    sourceLabel: "User planning document",
    badgeTone: "sea",
  },
  {
    id: "porto-ferro",
    slug: "porto-ferro",
    title: "Porto Ferro",
    category: "beach",
    shortDescription: "Wild surf-vibe beach with space, sunset, and teenager appeal.",
    longDescription:
      "A more rugged local-feeling beach with a broad sweep of sand, surf-school energy, and strong sunset potential when conditions line up.",
    area: "North Alghero",
    latitude: 40.6789,
    longitude: 8.2032,
    driveTimeMinutes: 25,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["surfing", "SUP", "sunset", "wild beach", "teenagers"],
    avoidIf: ["rough swimming conditions", "needing umbrella rentals"],
    tags: ["Beach", "Wild", "Surfing", "SUP", "Sunset", "Free"],
    localTip: "Bring your own shade and check the Maestrale before committing to a swim day.",
    weatherNotes: "Great for surf energy, not always ideal for casual swimmers.",
    parkingNotes: "Large free dirt parking by the pines.",
    foodNotes: "Il Baretto is the natural dinner add-on after sunset.",
    sourceLabel: "User document plus Guardian",
    badgeTone: "leaf",
  },
  {
    id: "le-saline",
    slug: "le-saline",
    title: "Le Saline / Kitezone",
    category: "activity",
    shortDescription: "Sports-focused coast for active teenagers.",
    longDescription:
      "More about movement than lounging: a good option when the family wants to lean into wind, space, and water sports.",
    area: "North-east of Alghero",
    latitude: 40.6104,
    longitude: 8.3522,
    driveTimeMinutes: 18,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["windsurfing", "SUP", "canoe", "active teens"],
    avoidIf: ["wanting classic soft-sand comfort"],
    tags: ["Activity", "Teen-friendly", "SUP", "Kayak", "Surfing"],
    localTip: "Best framed as an active outing rather than a lazy beach day.",
    sourceLabel: "User planning document",
    badgeTone: "coral",
  },
  {
    id: "sardigna-beach",
    slug: "sardigna-beach-le-saline",
    title: "Sardigna Beach Club",
    category: "beach",
    shortDescription: "Comfort setup with sunbeds and easy lunch.",
    longDescription:
      "Useful when the family wants beach-club convenience, a shaded lunch option, and fewer logistics decisions.",
    area: "Le Saline",
    latitude: 40.6121,
    longitude: 8.3571,
    driveTimeMinutes: 18,
    priceLevel: "medium",
    imageUrl:
      "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["comfort", "sunbeds", "easy lunch"],
    avoidIf: ["wanting free beach days"],
    tags: ["Beach", "Beach club", "Good lunch", "Comfort"],
    localTip: "Good compromise pick for mixed-energy beach days.",
    sourceLabel: "User planning document",
    badgeTone: "sand",
  },
  {
    id: "cala-cumpoltitu",
    slug: "cala-cumpoltitu",
    title: "Cala Cumpoltitu",
    category: "beach",
    shortDescription: "The postcard adventure cove for older teens and hikers.",
    longDescription:
      "A dramatic wild-cove choice with a rugged descent, clearer payoff for adventurous families, and very little built comfort.",
    area: "Alghero–Bosa road",
    latitude: 40.4925,
    longitude: 8.3611,
    driveTimeMinutes: 30,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1502780402662-acc01917a674?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["snorkelling", "adventure", "scenery", "older teenagers"],
    avoidIf: ["limited mobility", "midday heat", "needing facilities"],
    tags: ["Beach", "Wild", "Adventure", "Snorkelling"],
    localTip: "Bring water, food, and proper shoes. Treat it like an outing, not a casual beach stop.",
    sourceLabel: "User planning document",
    badgeTone: "leaf",
  },
  {
    id: "poglina",
    slug: "spiaggia-di-poglina",
    title: "Poglina / La Speranza",
    category: "beach",
    shortDescription: "The easier south-side alternative with amenities.",
    longDescription:
      "A practical swap for the scenic-road side of the coast when the family wants easier parking, lunch, and less hiking.",
    area: "South of Alghero",
    latitude: 40.5117,
    longitude: 8.3512,
    driveTimeMinutes: 20,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1502786129293-79981df4e689?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["easy access", "surf waves", "restaurant lunch"],
    avoidIf: ["seeking hidden-cove drama"],
    tags: ["Beach", "Easy parking", "Good lunch", "Surfing"],
    localTip: "Great to pair with the Alghero–Bosa drive without overcomplicating the day.",
    sourceLabel: "User planning document",
    badgeTone: "sand",
  },
  {
    id: "la-pelosa",
    slug: "la-pelosa",
    title: "La Pelosa",
    category: "excursion",
    shortDescription: "Iconic turquoise-water beach with strict access rules.",
    longDescription:
      "A bucket-list outing, but one that needs admin-level planning because access, timing, and sand-protection rules matter.",
    area: "Stintino",
    latitude: 40.9634,
    longitude: 8.2081,
    driveTimeMinutes: 50,
    priceLevel: "medium",
    bookingRequired: true,
    bookingUrl: "https://spiaggialapelosa.it/en/",
    officialUrl: "https://spiaggialapelosa.it/en/",
    imageUrl:
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["iconic day trip", "clear water", "special outing"],
    avoidIf: ["last-minute planning", "strict-rule fatigue"],
    tags: ["Day trip", "Needs booking", "Beach", "Teen-friendly"],
    localTip: "Check the official booking site before putting this into an itinerary.",
    weatherNotes: "Best on calm bright days. Avoid spontaneous same-day attempts.",
    sourceLabel: "Official La Pelosa booking site",
    badgeTone: "coral",
  },
  {
    id: "capo-caccia",
    slug: "capo-caccia-belvedere",
    title: "Capo Caccia Belvedere",
    category: "viewpoint",
    shortDescription: "The best big-sky sunset play.",
    longDescription:
      "Dramatic cliffs, family-photo energy, and a premium golden-hour payoff make this one of the easiest standout evenings to plan.",
    area: "Capo Caccia",
    latitude: 40.5656,
    longitude: 8.1588,
    driveTimeMinutes: 35,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["sunset", "family photos", "dramatic views"],
    avoidIf: ["late arrival", "poor footwear"],
    tags: ["Viewpoint", "Sunset", "Free", "Easy evening"],
    localTip: "Arrive early and park only in marked bays.",
    parkingNotes: "Small marked bays only; do not block traffic.",
    sourceLabel: "User planning document",
    badgeTone: "coral",
  },
  {
    id: "neptunes-grotto",
    slug: "neptunes-grotto",
    title: "Neptune's Grotto",
    category: "activity",
    shortDescription: "Signature cave visit with real timing and access rules.",
    longDescription:
      "One of the headline outings near Alghero, but it rewards families who handle reservations and arrival timing carefully.",
    area: "Capo Caccia",
    latitude: 40.5704,
    longitude: 8.1639,
    driveTimeMinutes: 35,
    priceLevel: "medium",
    bookingRequired: true,
    bookingUrl: "https://grottadinettuno.it/en/come-arrivare/",
    officialUrl: "https://grottadinettuno.it/en/come-arrivare/",
    imageUrl:
      "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["cloudy day", "dramatic outing", "family landmark"],
    avoidIf: ["heat-sensitive stair climbs", "last-minute arrivals"],
    tags: ["Activity", "Needs booking", "Cloudy day", "Family landmark"],
    localTip: "Book ahead and arrive early enough for the shuttle or stair access window.",
    weatherNotes: "Excellent non-beach option when the weather shifts.",
    sourceLabel: "Official Neptune's Grotto sources",
    badgeTone: "sea",
  },
  {
    id: "stintino-boat",
    slug: "stintino-boat-excursion",
    title: "Stintino Boat Excursion",
    category: "excursion",
    shortDescription: "Birthday-worthy boat day with natural pools and special-trip energy.",
    longDescription:
      "A stronger full-day memory-maker than a standard beach day, especially when the family wants one standout shared experience.",
    area: "Stintino / Asinara",
    latitude: 40.9526,
    longitude: 8.2267,
    driveTimeMinutes: 50,
    priceLevel: "expensive",
    bookingRequired: true,
    imageUrl:
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["birthday", "boat day", "teenagers", "special outing"],
    avoidIf: ["wanting a lazy morning", "seasickness"],
    tags: ["Excursion", "Needs booking", "Teen-friendly", "Special day"],
    localTip: "The 09:00 departure is the best balance of water, temperature, and crowd levels.",
    sourceLabel: "User planning document",
    badgeTone: "coral",
  },
  {
    id: "old-town",
    slug: "alghero-old-town",
    title: "Alghero Old Town",
    category: "town",
    shortDescription: "The easiest high-value evening in the whole trip.",
    longDescription:
      "Cobblestone streets, sea walls, gelato stops, and dinner options make this the most flexible non-beach favourite in the app.",
    area: "Alghero centre",
    latitude: 40.5598,
    longitude: 8.3154,
    driveTimeMinutes: 6,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["evening walk", "shops", "dinner", "gelato"],
    avoidIf: ["searching for a full-day outing"],
    tags: ["Town", "Evening", "No beach weather", "Easy"],
    localTip: "Best after a rest, with dinner timed for golden hour or later.",
    sourceLabel: "Sardinia and travel guides",
    badgeTone: "sand",
  },
  {
    id: "bastioni",
    slug: "bastioni-sunset-walk",
    title: "Bastioni Sunset Walk",
    category: "viewpoint",
    shortDescription: "Zero-stress sunset option right in town.",
    longDescription:
      "A low-effort family winner when everyone wants something nice but nobody wants another drive or big commitment.",
    area: "Alghero centre",
    latitude: 40.5582,
    longitude: 8.3096,
    driveTimeMinutes: 6,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["sunset", "stroll", "easy evening"],
    avoidIf: ["wanting a major excursion"],
    tags: ["Viewpoint", "Sunset", "Free", "No car needed"],
    localTip: "One of the best low-energy evening fillers in the app.",
    sourceLabel: "User planning document",
    badgeTone: "coral",
  },
  {
    id: "palmavera",
    slug: "nuraghe-palmavera",
    title: "Nuraghe Palmavera",
    category: "activity",
    shortDescription: "The culture break that balances a beach-heavy week.",
    longDescription:
      "A simple way to add history and variety without committing to a huge travel day.",
    area: "Near Porto Conte",
    latitude: 40.5958,
    longitude: 8.2834,
    driveTimeMinutes: 18,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["history", "cloudy day", "half-day"],
    avoidIf: ["only wanting water activities"],
    tags: ["Activity", "History", "Cloudy day", "Half day"],
    localTip: "Pair with Porto Conte or a relaxed lunch rather than stacking too much.",
    sourceLabel: "User planning document",
    badgeTone: "leaf",
  },
  {
    id: "punta-giglio",
    slug: "punta-giglio-porto-conte",
    title: "Punta Giglio / Porto Conte",
    category: "activity",
    shortDescription: "Active-day pick with e-bike and hike energy.",
    longDescription:
      "One of the better options when the family wants to earn views rather than just sit by the sea.",
    area: "Porto Conte",
    latitude: 40.5744,
    longitude: 8.1996,
    driveTimeMinutes: 24,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["e-bike", "hiking", "active family day"],
    avoidIf: ["very hot midday plans"],
    tags: ["Activity", "Adventure", "Views", "Cloudy day"],
    localTip: "Much better early or later in the day during hot weeks.",
    sourceLabel: "Travel guide research",
    badgeTone: "leaf",
  },
  {
    id: "bosa-drive",
    slug: "alghero-bosa-drive",
    title: "Alghero–Bosa Scenic Drive",
    category: "excursion",
    shortDescription: "A coastal road trip with strong visual payoff.",
    longDescription:
      "This is the flexible adventure route that can absorb a wild beach, an easy beach, or a town stop depending on energy.",
    area: "SP105 coastal road",
    latitude: 40.4701,
    longitude: 8.366,
    driveTimeMinutes: 45,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1468413253725-0d5181091126?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["scenic day", "paired stops", "cloudy weather"],
    avoidIf: ["wanting a short outing"],
    tags: ["Day trip", "Scenic", "Cloudy day", "Adventure"],
    localTip: "Best when built around one strong stop instead of trying to do everything.",
    sourceLabel: "User planning document",
    badgeTone: "sand",
  },
  {
    id: "bosa-town",
    slug: "bosa",
    title: "Bosa",
    category: "town",
    shortDescription: "Colourful river town for a varied day trip.",
    longDescription:
      "A pleasant change of rhythm with architecture, views, and a more relaxed non-beach feel.",
    area: "Bosa",
    latitude: 40.2997,
    longitude: 8.4985,
    driveTimeMinutes: 55,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["town stroll", "castle views", "paired day trip"],
    avoidIf: ["wanting a quick local plan"],
    tags: ["Town", "Day trip", "Cloudy day"],
    localTip: "Pairs naturally with Poglina or the scenic drive.",
    sourceLabel: "User planning document",
    badgeTone: "sand",
  },
  {
    id: "piazza-civica",
    slug: "piazza-civica",
    title: "Piazza Civica",
    category: "viewpoint",
    shortDescription: "The old town's main square for an easy evening stroll.",
    longDescription:
      "The social heart of the historic centre, ringed by arcaded palazzi and cafe terraces. A natural stop before or after the Bastioni sunset walk.",
    area: "Alghero Old Town",
    latitude: 40.559,
    longitude: 8.3165,
    walkTimeMinutes: 15,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["evening stroll", "people watching", "aperitivo"],
    avoidIf: ["wanting a quiet, empty square in high season"],
    tags: ["Town", "Old Town", "Evening", "Easy"],
    localTip: "Best after 18:00 once the heat drops and the terraces fill up.",
    sourceLabel: "Tripadvisor via Apify",
    badgeTone: "sand",
  },
  {
    id: "torre-san-giovanni",
    slug: "torre-di-san-giovanni",
    title: "Torre di San Giovanni",
    category: "viewpoint",
    shortDescription: "Historic seafront watchtower on the old town bastions.",
    longDescription:
      "One of the Catalan-era towers guarding Alghero's sea walls, with good photo angles over the harbour and bastioni.",
    area: "Alghero Old Town",
    latitude: 40.5586,
    longitude: 8.316,
    walkTimeMinutes: 16,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["photos", "history", "short walk"],
    avoidIf: ["short on time for the full bastioni loop"],
    tags: ["Landmark", "Old Town", "History", "Free"],
    localTip: "Combine with Torre di San Giacomo for a short tower-to-tower walk.",
    sourceLabel: "Tripadvisor via Apify",
    badgeTone: "sea",
  },
  {
    id: "museo-archeologico-alghero",
    slug: "museo-archeologico-alghero",
    title: "Museo Archeologico della Città di Alghero",
    category: "activity",
    shortDescription: "Compact museum covering the area's Nuragic and Catalan history.",
    longDescription:
      "A useful indoor option for a hot afternoon or a cloudy day, giving context to Nuraghe Palmavera and the old town before or after visiting them.",
    area: "Alghero Old Town",
    latitude: 40.5593,
    longitude: 8.3172,
    walkTimeMinutes: 14,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["cloudy day", "history", "shaded break"],
    avoidIf: ["low interest in museums"],
    tags: ["Museum", "Old Town", "Cloudy day", "Indoor"],
    localTip: "Good pairing with Palmavera for a full Nuragic-history day.",
    sourceLabel: "Tripadvisor via Apify",
    badgeTone: "sand",
  },
  {
    id: "parco-porto-conte",
    slug: "parco-naturale-porto-conte",
    title: "Parco Naturale Regionale di Porto Conte",
    category: "excursion",
    shortDescription: "Protected coastal nature reserve around Porto Conte bay.",
    longDescription:
      "Covers the wilder ground between Alghero and Capo Caccia, with trails, birdlife, and views that reward slower exploring beyond the beach stops.",
    area: "Porto Conte",
    latitude: 40.6031,
    longitude: 8.2079,
    driveTimeMinutes: 20,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["nature walk", "wildlife", "quiet morning"],
    avoidIf: ["wanting a fast, structured visit"],
    tags: ["Nature", "Excursion", "Porto Conte", "Free"],
    localTip: "Pairs well with Capo Caccia or Punta Giglio on the same outing.",
    sourceLabel: "Tripadvisor via Apify",
    badgeTone: "leaf",
  },
  {
    id: "chiosco-bombarde",
    slug: "il-chiosco-le-bombarde",
    title: "Il Chiosco Le Bombarde",
    category: "restaurant",
    shortDescription: "Budget beach lunch that keeps the day moving.",
    longDescription:
      "A very useful pick for staying near the water without turning lunch into a whole separate event.",
    area: "Le Bombarde",
    latitude: 40.6011,
    longitude: 8.2896,
    driveTimeMinutes: 15,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["quick lunch", "budget", "beach day"],
    avoidIf: ["special dinner mood"],
    tags: ["Food", "Budget", "Quick lunch", "Near beach"],
    localTip: "Great for low-friction lunch on a teen beach day.",
    sourceLabel: "User planning document",
    badgeTone: "sand",
  },
  {
    id: "da-bruno",
    slug: "bar-ristorante-da-bruno",
    title: "Bar Ristorante Da Bruno",
    category: "restaurant",
    shortDescription: "Casual and easy for pizza slices or quick pasta near Le Bombarde.",
    longDescription:
      "A practical rather than fancy stop that helps the family stay flexible on a north-coast day.",
    area: "Le Bombarde",
    latitude: 40.6005,
    longitude: 8.2915,
    driveTimeMinutes: 15,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["quick pasta", "casual", "teenagers"],
    avoidIf: ["looking for signature local cuisine"],
    tags: ["Food", "Budget", "Pizza", "Near beach"],
    localTip: "A dependable fallback for beach-hungry teenagers.",
    sourceLabel: "User planning document",
    badgeTone: "sand",
  },
  {
    id: "le-ninfe",
    slug: "le-ninfe",
    title: "Le Ninfe",
    category: "restaurant",
    shortDescription: "The lunch anchor for a calm Mugoni day.",
    longDescription:
      "Comfortable, shaded, and easy to pair with a sheltered beach plan when the family wants simplicity.",
    area: "Mugoni",
    latitude: 40.5868,
    longitude: 8.2121,
    driveTimeMinutes: 20,
    priceLevel: "medium",
    imageUrl:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["beach club lunch", "shade", "family ease"],
    avoidIf: ["keeping costs very low"],
    tags: ["Food", "Near beach", "Good lunch", "Comfort"],
    localTip: "One of the easiest places to pair with a calmer family beach day.",
    sourceLabel: "User planning document",
    badgeTone: "sea",
  },
  {
    id: "porto-ferro-baretto",
    slug: "il-baretto-di-porto-ferro",
    title: "Il Baretto di Porto Ferro",
    category: "restaurant",
    shortDescription: "Surf-vibe dinner add-on for Porto Ferro sunsets.",
    longDescription:
      "A strong mood match for Porto Ferro itself: laid-back, teen-friendly, and better for vibe than formality.",
    area: "Porto Ferro",
    latitude: 40.6791,
    longitude: 8.2027,
    driveTimeMinutes: 25,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["teenagers", "burgers", "sunset dinner"],
    avoidIf: ["formal meal expectations"],
    tags: ["Food", "Budget", "Teen-friendly", "Sunset", "Near beach"],
    localTip: "Best used to complete a Porto Ferro sunset route.",
    sourceLabel: "User planning document",
    badgeTone: "coral",
  },
  {
    id: "hermeu-kiosk",
    slug: "lido-hermeu-kiosk",
    title: "Lido Hermeu Kiosk",
    category: "restaurant",
    shortDescription: "Useful beach-food stop at Maria Pia.",
    longDescription:
      "Straightforward panini and salad option that lowers the friction of choosing Maria Pia for a whole day.",
    area: "Maria Pia",
    latitude: 40.5821,
    longitude: 8.3081,
    driveTimeMinutes: 9,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["quick lunch", "beach day", "easy logistics"],
    avoidIf: ["special occasion dinner"],
    tags: ["Food", "Budget", "Quick lunch", "Near beach"],
    localTip: "Makes Maria Pia work well as a low-drama full-day beach plan.",
    sourceLabel: "User planning document",
    badgeTone: "sand",
  },
  {
    id: "al-tuguri",
    slug: "al-tuguri",
    title: "Al Tuguri",
    category: "restaurant",
    shortDescription: "A strong special-dinner option for local Algherese cooking.",
    longDescription:
      "This is the app's 'worth booking' dinner if the family wants one meal that feels more rooted in place.",
    area: "Old Town",
    latitude: 40.5589,
    longitude: 8.3182,
    driveTimeMinutes: 6,
    priceLevel: "expensive",
    bookingRequired: true,
    imageUrl:
      "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["special dinner", "local cuisine", "adults plus family"],
    avoidIf: ["last-minute casual mood"],
    tags: ["Food", "Needs booking", "Local dishes", "Old Town"],
    localTip: "Book a few days ahead during July and August.",
    sourceLabel: "Aigua insider guide",
    badgeTone: "coral",
  },
  {
    id: "lo-romani",
    slug: "lo-romani",
    title: "Lo Romani",
    category: "restaurant",
    shortDescription: "Another good local-cooking candidate for a proper dinner.",
    longDescription:
      "One of the stronger choices when the family wants typical Sardinian and Algherese flavours without going generic.",
    area: "Alghero",
    latitude: 40.5591,
    longitude: 8.3188,
    driveTimeMinutes: 8,
    priceLevel: "medium",
    bookingRequired: true,
    imageUrl:
      "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["local cuisine", "family dinner"],
    avoidIf: ["quick lunch"],
    tags: ["Food", "Needs booking", "Local dishes"],
    localTip: "Worth using in the app for 'try local food' pathways.",
    sourceLabel: "Aigua insider guide",
    badgeTone: "sea",
  },
  {
    id: "mabrouk",
    slug: "ristorante-mabrouk",
    title: "Ristorante Mabrouk",
    category: "restaurant",
    shortDescription: "Seafood-led dinner with stronger adult appeal.",
    longDescription:
      "More of a deliberate dinner than a casual stop, and one that benefits from planning ahead.",
    area: "Alghero",
    latitude: 40.5579,
    longitude: 8.3164,
    driveTimeMinutes: 7,
    priceLevel: "expensive",
    bookingRequired: true,
    imageUrl:
      "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["seafood", "special dinner", "adults"],
    avoidIf: ["budget meals", "very picky teen menus"],
    tags: ["Food", "Needs booking", "Seafood"],
    localTip: "Treat this as a reservation-first dinner candidate.",
    sourceLabel: "Local recommendation roundups",
    badgeTone: "coral",
  },
  {
    id: "caragol",
    slug: "trattoria-caragol",
    title: "Trattoria Caragol",
    category: "restaurant",
    shortDescription: "Casual local flavours in the historic centre.",
    longDescription:
      "A more approachable old-town food option that still feels grounded in local flavour.",
    area: "Historic centre",
    latitude: 40.5585,
    longitude: 8.3173,
    driveTimeMinutes: 7,
    priceLevel: "medium",
    imageUrl:
      "https://images.unsplash.com/photo-1514326640560-7d063ef2aed5?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["casual local dinner", "old town"],
    avoidIf: ["super-fast snack stop"],
    tags: ["Food", "Local dishes", "Old Town", "Casual"],
    localTip: "Easy to slot after an Old Town wander.",
    sourceLabel: "Food guides",
    badgeTone: "sea",
  },
  {
    id: "milese",
    slug: "il-milese",
    title: "Il Milese",
    category: "restaurant",
    shortDescription: "Reliable sandwich and snack stop in town.",
    longDescription:
      "Not a destination dinner, but a very useful casual option for feeding the family between plans.",
    area: "Alghero",
    latitude: 40.5597,
    longitude: 8.3201,
    driveTimeMinutes: 6,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["cheap eats", "snack", "low fuss"],
    avoidIf: ["looking for a formal sit-down meal"],
    tags: ["Food", "Budget", "Quick lunch"],
    localTip: "Useful in low-energy evenings when a simple bite is enough.",
    sourceLabel: "Gambero Rosso guide",
    badgeTone: "sand",
  },
  {
    id: "licchita",
    slug: "licchita-pizzeria-moderna",
    title: "Licchita Pizzeria Moderna",
    category: "restaurant",
    shortDescription: "Pizza-first easy win for the teenagers.",
    longDescription:
      "One of the strongest low-drama group picks when you want a dependable casual dinner everyone will accept.",
    area: "Alghero",
    latitude: 40.5608,
    longitude: 8.3194,
    driveTimeMinutes: 8,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["pizza", "cheap eats", "teenagers"],
    avoidIf: ["seeking distinctive local dishes"],
    tags: ["Food", "Budget", "Pizza", "Teen-friendly"],
    localTip: "Keep this around for a practical family reset meal.",
    sourceLabel: "Tripadvisor popularity check",
    badgeTone: "coral",
  },
  {
    id: "ok-pizza",
    slug: "ok-pizza-evolution",
    title: "Ok Pizza Evolution",
    category: "restaurant",
    shortDescription: "Another easy pizza safety valve.",
    longDescription:
      "A backup casual meal so dinner planning never depends on one single venue.",
    area: "Alghero",
    latitude: 40.5601,
    longitude: 8.3207,
    driveTimeMinutes: 8,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["pizza", "cheap eats", "quick dinner"],
    avoidIf: ["special occasion meals"],
    tags: ["Food", "Budget", "Pizza"],
    localTip: "Handy backup if other dinner plans fall through.",
    sourceLabel: "Tripadvisor popularity check",
    badgeTone: "sand",
  },
  {
    id: "gelato-934",
    slug: "gelateria-9-3-4",
    title: "Gelateria Artigianale 9 3/4",
    category: "restaurant",
    shortDescription: "Easy dessert stop after Old Town or Bastioni.",
    longDescription:
      "Small, simple, but high usefulness because it upgrades easy evenings with almost no effort.",
    area: "Alghero",
    latitude: 40.5588,
    longitude: 8.3189,
    driveTimeMinutes: 6,
    priceLevel: "budget",
    imageUrl:
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["dessert", "Old Town", "post-dinner walk"],
    avoidIf: ["needing a full meal"],
    tags: ["Food", "Dessert", "Old Town", "Cheap eats"],
    localTip: "Perfect to close the Bastioni sunset route.",
    sourceLabel: "Tripadvisor popularity check",
    badgeTone: "coral",
  },
  {
    id: "sa-mandra",
    slug: "azienda-agrituristica-sa-mandra",
    title: "Azienda Agrituristica Sa Mandra",
    category: "restaurant",
    shortDescription: "Farm-to-table set menu just outside town.",
    longDescription:
      "A working farm restaurant serving a fixed multi-course Sardinian menu from its own produce. Rustic, filling, and a strong pick when the family wants a proper sit-down meal with local character.",
    area: "Near Fertilia",
    latitude: 40.6109,
    longitude: 8.2841,
    driveTimeMinutes: 15,
    priceLevel: "medium",
    bookingRequired: true,
    imageUrl:
      "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["local cuisine", "family dinner", "farm setting"],
    avoidIf: ["wanting a quick, light meal"],
    tags: ["Food", "Needs booking", "Local dishes", "Agriturismo"],
    localTip: "Come hungry — it's a long fixed menu, not an à la carte stop.",
    sourceLabel: "Tripadvisor via Apify",
    badgeTone: "leaf",
  },
  {
    id: "alamo-cucina",
    slug: "alamo-cucina-di-mare",
    title: "Alamo - Cucina Di Mare Sardo Catalana",
    category: "restaurant",
    shortDescription: "Seafood-forward Catalan-Sardinian dinner in town.",
    longDescription:
      "One of the higher-rated seafood dinners in Alghero, blending Catalan and Sardinian coastal cooking. Works well as the trip's one memorable seafood night.",
    area: "Alghero",
    latitude: 40.5583,
    longitude: 8.317,
    driveTimeMinutes: 7,
    priceLevel: "expensive",
    bookingRequired: true,
    imageUrl:
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["seafood", "special dinner", "local flavours"],
    avoidIf: ["budget night", "picky eaters"],
    tags: ["Food", "Needs booking", "Seafood", "Local dishes"],
    localTip: "Book ahead — it's popular with both locals and visitors.",
    sourceLabel: "Tripadvisor via Apify",
    badgeTone: "coral",
  },
  {
    id: "trattoria-da-mirko",
    slug: "trattoria-da-mirko",
    title: "Trattoria Da Mirko",
    category: "restaurant",
    shortDescription: "Well-reviewed casual trattoria in the historic centre.",
    longDescription:
      "A dependable, high-volume trattoria with consistently strong reviews — a safer bet than hunting for a table on the fly during peak season.",
    area: "Alghero Old Town",
    latitude: 40.5592,
    longitude: 8.3178,
    walkTimeMinutes: 15,
    priceLevel: "medium",
    imageUrl:
      "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["casual dinner", "old town", "reliable choice"],
    avoidIf: ["wanting a quiet, low-key spot"],
    tags: ["Food", "Old Town", "Local dishes"],
    localTip: "Popular — arrive early or book to skip the wait.",
    sourceLabel: "Tripadvisor via Apify",
    badgeTone: "sea",
  },
  {
    id: "ristorante-enhorabona",
    slug: "ristorante-enhorabona",
    title: "Ristorante Enhorabona",
    category: "restaurant",
    shortDescription: "Consistently well-rated dinner spot in town.",
    longDescription:
      "A crowd-pleasing option with a large base of strong reviews, useful as a flexible dinner choice that rarely disappoints.",
    area: "Alghero",
    latitude: 40.5599,
    longitude: 8.3196,
    driveTimeMinutes: 8,
    priceLevel: "medium",
    imageUrl:
      "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["family dinner", "reliable choice"],
    avoidIf: ["seeking something highly distinctive"],
    tags: ["Food", "Local dishes", "Family friendly"],
    localTip: "A safe fallback when other reservations fall through.",
    sourceLabel: "Tripadvisor via Apify",
    badgeTone: "sand",
  },
  {
    id: "book-ahead",
    slug: "book-ahead-restaurants",
    title: "Book Ahead in July and August",
    category: "local_tip",
    shortDescription: "Popular dinners can disappear a few days out.",
    longDescription:
      "Use this as a family planning rule: if a restaurant matters, do not leave it to same-day luck in peak season.",
    area: "Alghero",
    latitude: 40.5607,
    longitude: 8.3193,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["peak-season planning"],
    avoidIf: [],
    tags: ["Local tip", "Needs booking", "Food"],
    localTip: "Admin should convert strong dinner votes into bookings early.",
    sourceLabel: "Local recommendation pattern",
    badgeTone: "coral",
  },
  {
    id: "wind-tip",
    slug: "check-maestrale-before-porto-ferro",
    title: "Check Maestrale Before Porto Ferro",
    category: "local_tip",
    shortDescription: "Wind can make Porto Ferro thrilling or rough.",
    longDescription:
      "A simple weather rule that prevents forcing a swim day into conditions that want to be a surf or scenic day instead.",
    area: "North-west coast",
    latitude: 40.6789,
    longitude: 8.2032,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["weather logic"],
    avoidIf: [],
    tags: ["Local tip", "Weather", "Surfing"],
    localTip: "Prefer Mugoni or Porto Conte when west-facing beaches look exposed.",
    sourceLabel: "User planning notes",
    badgeTone: "leaf",
  },
  {
    id: "wild-beach-tip",
    slug: "bring-water-for-wild-beaches",
    title: "Pack Properly for Wild Beaches",
    category: "local_tip",
    shortDescription: "Wild beaches are outing days, not convenience days.",
    longDescription:
      "Use this rule for Cala Cumpoltitu and similar picks: water, food, shoes, shade, and realistic energy expectations matter.",
    area: "South-west coves",
    latitude: 40.4925,
    longitude: 8.3611,
    priceLevel: "free",
    imageUrl:
      "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1200&q=80",
    bestFor: ["adventure planning"],
    avoidIf: [],
    tags: ["Local tip", "Adventure", "Wild"],
    localTip: "Great for adventurous days, not for low-prep moods.",
    sourceLabel: "User planning notes",
    badgeTone: "sand",
  },
];

export const initialVotes: VoteRecord[] = [
  { userId: "fred", placeId: "mugoni", vote: "must_do", ranking: 2, comment: "Calmer water fallback." },
  { userId: "simona", placeId: "old-town", vote: "must_do", ranking: 1, comment: "Best easy evening." },
  { userId: "david", placeId: "bombarde", vote: "must_do", ranking: 1, comment: "SUP and clear water." },
  { userId: "philippe", placeId: "porto-ferro", vote: "must_do", ranking: 2, comment: "Feels more adventurous." },
  { userId: "fred", placeId: "neptunes-grotto", vote: "interested", ranking: 5, comment: "Good cloudy-day anchor." },
  { userId: "simona", placeId: "al-tuguri", vote: "interested", ranking: 4, comment: "One proper local dinner." },
  { userId: "david", placeId: "stintino-boat", vote: "must_do", ranking: 3, comment: "Birthday pick." },
  { userId: "philippe", placeId: "la-pelosa", vote: "interested", ranking: 4, comment: "Worth it if booked." },
  { userId: "fred", placeId: "cala-cumpoltitu", vote: "not_for_me", comment: "Maybe too much in peak heat." },
  { userId: "simona", placeId: "mabrouk", vote: "must_do", ranking: 3, comment: "Adults would love one seafood dinner." },
];

export const suggestedCollections: Collection[] = [
  {
    id: "easy-first-day",
    title: "Easy first day",
    description: "Low-pressure arrival flow with a quick beach and easy evening.",
    placeSlugs: ["lido-di-alghero", "alghero-old-town", "bastioni-sunset-walk", "gelateria-9-3-4"],
  },
  {
    id: "best-teen-beach-day",
    title: "Best teenager beach day",
    description: "Energy, water toys, and a lunch plan that keeps everyone moving.",
    placeSlugs: ["le-bombarde", "il-chiosco-le-bombarde"],
  },
  {
    id: "comfort-beach-day",
    title: "Comfort beach day",
    description: "Smooth logistics with calmer decisions from parking to lunch.",
    placeSlugs: ["spiaggia-di-maria-pia", "lido-hermeu-kiosk"],
  },
  {
    id: "wild-surf-vibe",
    title: "Wild surf vibe",
    description: "For the day when the family wants something less polished and more memorable.",
    placeSlugs: ["porto-ferro", "il-baretto-di-porto-ferro"],
  },
  {
    id: "cloudy-day",
    title: "Cloudy day",
    description: "A non-beach sequence that still feels like a proper outing.",
    placeSlugs: ["neptunes-grotto", "nuraghe-palmavera", "alghero-old-town"],
  },
];
